### ISSUE TITLE
Testing http proxy on uaclient

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1458]
To test the use of an `http proxy` on uaclient, we must ensure that the proxy is being used on http requests issued by different paths:

* `apt`: We must set a proxy config file on `etc/apt/apt.conf.d/` containing the following directives:

```
Acquire::http::Proxy "<proxy-url>:<proxy-port:";
Acquire::https::Proxy "<proxy-url>:<proxy-port:";
```

* `ubuntu-advantage-tools`: Our tool makes request through `urllib.urlopen` calls. This tools is already configured to use
                                             `*_proxy` environment variables by default. Therefore, to ensure that uaclient is using a proxy,
                                             we need to set up both `http_proxy` and `http_proxy` environment variables.
                                             
This can all be achieved with create an instance with the following `cloud-init userdata`:
```
#cloud-config 
apt:
  http_proxy: <proxy-url>:<proxy-port:
  https_proxy: <proxy-url>:<proxy-port:
write_files:
    - path: /etc/environment
      content: |
        http_proxy="<proxy-url>:<proxy-port:"
        https_proxy="<proxy-url>:<proxy-port:"
      append: true
```

Now, to fully test that, we need to create a `proxy server` to handle those requests. We can do that by following these steps:

1. Launch a `focal` machine on a cloud-provider (GCP, for example).
2. Install the `squid` package on the machine:
    `apt-get install squid`
3. Edit the `/etc/squid/squid.conf` file by adding the following lines to it:
    ```
    acl all src 0.0.0.0/0
    http_access allow all
    ```
    This configuration will allow any IP address to reach and use the proxy server:
    **PS**: It is important to add those lines before the `http_access deny all` configuration.
4. Restart the `squid` service
    `systemctl restart squid.service`
5. **Certify that the firewall in your instance allow tcp connections on the proxy port**
    `squid` by default will expect connection on the `3128`. On GCP, it seems that the `3389` port is already enabled for tcp
    connections by default, so we can use it on GCP. Otherwise, we need to update the firewall rules to allow tcp access to the
    necessary port
6. After this is all done, you can edit the `cloud-init userdata` file with the IP of the proxy server machine and port used in the
    configuration of `squid`. After launching the image you can verify if the `uaclient`operations are going through the proxy
    by looking at `/var/log/squid/access.log` file.
